### PR TITLE
Polymer2.0 preview

### PR DESCRIPTION
**Pull request by mdwragg**
Ready for Polymer 1.x/2.x hybrid support.

@davidrleonard - can you check I set this PR up right, I got thrown by the forked base and github went a bit nuts on me....

### CODE REVIEW

**Comment by mdwragg** [comment]
@davidrleonard - can we use this on webcomponents 0.7.x? Or do we not care as 0.7.x is the variant, 1.x is mainline? 🤔 

https://github.com/PredixDev/px-icon-set/pull/11/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR12

**Comment by davidrleonard** [comment]
Oooh... good question. I think loading the component through the index.html will be broken in webcomponents 0.7.x. Let me see how we should handle that.

**Comment by davidrleonard** [comment]
Fixed this. It looks like we should be loading `webcomponentsjs/webcomponents-lite.js` everywhere for our polyfills if we want them to work with webcomponents 0.x or 1.x. That file exists in both. The file we usually load right now, webcomponents-lite.min.js, exists in 0.x but is gone in 1.x. Oh well.

**Review by davidrleonard — APPROVED** [review]

**Review by randyaskin — APPROVED** [review]

**Comment by mdwragg** [comment]
@davidrleonard Yeah, I've been switching to wc-lite.js as 'min' has gone. Works in both variants.

**Pull request merged**
